try:
    x = 3
    a ='a'
    print(x/a)
except Exception as erro:
    print(f'{erro}')

